#!/bin/bash
dnf update -y
dnf install mariadb105-server -y
systemctl restart mariadb



https://docs.aws.amazon.com/ko_kr/AmazonRDS/latest/UserGuide/USER_ConnectToInstance.html

https://dev.classmethod.jp/articles/ec2-mysql-install-confilicting-requests-error-kr/
